export const apiRoutes = {
    getAppSettings: '/appsettings',
    getNobreakById: '/nobreak',
    getNobreaks: '/nobreaks',
    deleteNobreak: '/nobreak',
    getMachines: '/machines',
    getMachineById: '/machine',
    getRules: '/rules',
    getRuleById: '/rule',
    getArguments: '/arguments',
    getArgumentById: '/argument',
    getCredentials: '/credentials',
    getCredentialById: '/credential',
    getSensorById: '/sensor',
    getSensors: '/sensors',
    getSensorData: '/sensor',
    postWolMachine: '/machine/wol',
    postShutdownMachine: '/machine/shutdown',
    getOperationalSystems: '/machine/operational-systems',
  };