version: "3.2"
services:
  api:
    env_file: .deploy.env
    hostname: dac-api
    image: ghcr.io/antoniolago/datacenter-automated-controller-api:v0.1.82
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
      - "7:7/udp"
      - "9:9/udp"
    volumes:
      - "/opt/datacenter-automated-controller/nut/:/nut/"
      - "/opt/datacenter-automated-controller/api/app/db:/api/app/db/"
      - "/dev:/dev"
    networks:
      - datacenter-automated-controller
    depends_on:
      - redis
  frontend:
    image: ghcr.io/antoniolago/datacenter-automated-controller-front:v0.1.82
    ports:
      - 8090:80
    depends_on:
      - api
  nut:
    env_file: .deploy.env
    image: ghcr.io/antoniolago/datacenter-automated-controller-nut:v0.1.82
    privileged: true
    ports:
      - "3493:3493"
    volumes:
      - "/opt/datacenter-automated-controller/nut/:/etc/nut/"
      - "/opt/datacenter-automated-controller/shared:/shared"
    devices:
      - "/dev:/dev" #YOUR UPS's USB PORT
    networks:
      - datacenter-automated-controller
    depends_on:
      - api
  nut-launcher:
    restart: on-failure
    env_file: .deploy.env
    image: ghcr.io/antoniolago/datacenter-automated-controller-nut-launcher:v0.1.82
    depends_on:
      - api
      - nut
    networks:
      - datacenter-automated-controller

  redis:
    image: redis
    volumes:
      - "/opt/datacenter-automated-controller/redis:/data"
    ports:
      - "6379:${REDIS_PORT}"
    networks:
      - datacenter-automated-controller

  rule-applier:
    image: ghcr.io/antoniolago/datacenter-automated-controller-rule-applier:v0.1.82
    volumes:
      - "/opt/datacenter-automated-controller/rule-applier/:/app"
    networks:
      - datacenter-automated-controller

networks: 
  datacenter-automated-controller:
    driver: bridge
