- name: Shutdown machine
  # become: true
  hosts: all
  # vars:
  #   ansible_ssh_private_key_file: /ssh/SNPXX/id_pub
  tasks:
    - name: Shutdown Windows machine
      win_command: "shutdown /s /t 0"