FROM python:3.7.16-alpine3.16
WORKDIR /app
ENV PYTHONPATH=/shared:$PYTHONPATH

RUN pip install --upgrade pip
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY ./rule-applier /rule-applier
COPY ./shared /shared
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
CMD ["python", "/rule_applier/main.py"]