- name: Shutdown machine
  become: true
  tasks:
    - name: Shutdown Linux machine
      shell: "shutdown now"
      when: "'ansible_os_family' in hostvars[inventory_hostname] and hostvars[inventory_hostname]['ansible_os_family'] != 'Windows'"

    - name: Shutdown Windows machine
      win_shell: "shutdown /s /t 0"
      when: "'ansible_os_family' in hostvars[inventory_hostname] and hostvars[inventory_hostname]['ansible_os_family'] == 'Windows'"