# ------------------------------------------------------
# NPM INSTALL CACHE
# ------------------------------------------------------
# Cria uma imagem de cache apenas para o node_modules
FROM node:20-alpine as node_cache
WORKDIR /cache
# Instalando dependências da aplicação e armazenando em cache.
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --network-timeout 100000

# ------------------------------------------------------
# Build da aplicação
# ------------------------------------------------------
FROM node_cache as build

WORKDIR /src/odse
COPY --from=node_cache /cache/ .
# Copy source files, and possibily invalidate so we have to rebuild
COPY . ./
# Builda a aplicação para o deploy
RUN yarn run build

# ------------------------------------------------------
# Webserver para a aplicação
# ------------------------------------------------------
FROM nginx:1.25.1
COPY --from=build /src/odse/dist /usr/share/nginx/html
#Carrega configuração nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
EXPOSE 80

RUN chmod -R 755 /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]