FROM alpine:3.17.2
#RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update
RUN apk add --no-cache nut openssh-server
RUN mkdir -p /var/run/nut
VOLUME ["/sys/fs/cgroup"]
#SSH INSTALL
COPY ./nut/ssh/ /keys/
RUN mkdir -p /root/.ssh \
    && chmod 0700 /root/.ssh \
    && cat /keys/id_rsa.pub >> /root/.ssh/authorized_keys \
    && apk add openrc openssh \
    && ssh-keygen -A \
    && echo -e "PasswordAuthentication no" >> /etc/ssh/sshd_config \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel \
    && chown nut /var/run/nut
COPY ./nut/* /etc/nut/copy
ENTRYPOINT ["sh", "-c", "rc-status; rc-service sshd start; service sshd restart; cp /etc/nut/copy /etc/nut; tail -f /dev/null;"]