name: Build & publish Docker images
on:
  push:
    tags:
      - v*
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: front/Dockerfile_deploy
            image: ghcr.io/antoniolago/datacenter-automated-controller-front
            context: ./front
            platform: linux/arm64
          - dockerfile: api/Dockerfile_deploy
            image: ghcr.io/antoniolago/datacenter-automated-controller-api
            context: ./
            platform: linux/arm64
          - dockerfile: nut/Dockerfile_deploy
            image: ghcr.io/antoniolago/datacenter-automated-controller-nut
            context: ./
            platform: linux/arm64
          - dockerfile: nut-launcher/Dockerfile_deploy
            image: ghcr.io/antoniolago/datacenter-automated-controller-nut-launcher
            context: ./
            platform: linux/arm64
          - dockerfile: rule-applier/Dockerfile
            image: ghcr.io/antoniolago/datacenter-automated-controller-rule-applier
            context: ./rule-applier
            platform: linux/arm64
    permissions:
      contents: write
      packages: write
    steps:
      - name: Generate build ID
        id: prep
        run: |
          ref=${GITHUB_REF##*/}
          TAG=${{ github.event.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          tags: |
            ${{ env.VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ matrix.image }}:cache
          cache-to: type=registry,ref=${{ matrix.image }}:cache,mode=max
